package:
  name: cosign
  version: 1.13.1
  epoch: 0
  description: Container Signing
  target-architecture:
    - all
  copyright:
    - license: Apache-2.0
      paths:
        - "*"
  dependencies:
    runtime:
      - ca-certificates-bundle

environment:
  contents:
    repositories:
      - https://dl-cdn.alpinelinux.org/alpine/edge/main
      - https://dl-cdn.alpinelinux.org/alpine/edge/community
      - https://dl-cdn.alpinelinux.org/alpine/edge/testing
    packages:
      - busybox
      - ca-certificates-bundle
      - go

pipeline:
  - uses: fetch
    with:
      uri: https://github.com/sigstore/cosign/archive/v${{package.version}}/cosign-v${{package.version}}.tar.gz
      expected-sha256: 496583e9a3e07f16ff18f3734ca69398ef7091336fe74adaf8012715656bb920
  - runs: |
      CGO_ENABLED=0 go build \
        -trimpath -ldflags "-buildid= -X sigs.k8s.io/release-utils/version.gitVersion=${{package.version}}" \
        -o "${{targets.destdir}}/usr/bin/cosign" ./cmd/cosign